services:
  dual-n-back:
    image: ghcr.io/cozy-space/ewmt:main
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      AMOUNT_OF_BLOCKS_TO_PLAY: "15"
    volumes:
      - ./userdata:/usr/src/app/userdata
